### ISSUE TITLE
[Arcade] Taiga Spleef

### ISSUE THREAD

**Issue by Preinstalled** [Warzone/PublicMaps#125]
### Map Name

Taiga Spleef

### Map Description & Gamemode

10v10 Spleef Map based on theme "Taiga" 

### Map XML

https://gist.github.com/Preinstalled/1d3bfb2d6ad839ff3f8846fa43464aec

### Screenshot

![map](https://user-images.githubusercontent.com/75170440/217944589-8921c1ab-6354-482a-9db8-721c282c9944.png)

### Map Download

[Taiga Spleef.zip](https://github.com/Warzone/PublicMaps/files/10701726/Taiga.Spleef.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by TheRealPear** [comment]
This has been loaded onto Warzone. In the future, please don't ping me repeatedly to add maps, we will get to it as soon as possible. Additionally, you gave credit to a person that was not involved in this map's creation (and hasn't been on the unofficial mapmaking server for 5 months).

As for the XML, I have demoted the 2nd author to contributor as it would be more appropriate. You also had two kits with some items using the team-color attributes, which is redundant since you can assign both teams the same kit and save some lines. You also did not resize the map.png (and three other maps) to the resolution that is already listed in the README and the checklist.

Regardless, thank you for the submission.
