### ISSUE TITLE
[Bug] There are 1 too many arrows in the wool rooms

### ISSUE THREAD

**Issue by Mew2K** [Warzone/PublicMaps#97]
### Map Name

Snow Level

### Bug Type

Map/World build

### Description

On the map Snow Level, there are exactly 432 arrows in each wool room, but players already have infinity bows. I am not quite sure how attackers can take advantage of this excessive arrow supply in order to safely transport the wool back to their base, as infinity plus 432 is still equal to infinity. Therefore, I propose that these arrows be removed from the wool room chests, or perhaps instead, add some power 1, infinity 0 bows to the chests in order to give the arrows a purpose (if there already is a power bow somewhere on the map that I have simply not discovered, then I am sorry for wasting your time).

Thank you!

### Screenshots or Videos (if applicable)

https://imgur.com/a/TsKwyke
https://imgur.com/a/GXj0luu

**Comment by bearyr** [comment]
I recognize I'm getting to this issue a little late, but nonetheless I'll respond to your points.

I agree that the extra arrows in the wool room are obsolete, though I disagree with adding power 1 bows to the wool room chests - it's not like it's necessarily difficult to get out of the wool room because it's difficult to kill players, moreso it's annoying because you're provided little cover when trying to get out, but the wool lane is narrow enough that power 1 bows are not needed. That's at least how I feel about the map.

**Comment by Mew2K** [comment]
I agree with you. I do not think adding power 1 bows to this map makes any sense.

**Comment by BTKingly** [comment]
It sounds like removing the unneeded arrows is the easiest and favoured solution.

Done here - [f749a01](https://github.com/Warzone/PublicMaps/commit/f749a01aad7312ed4956b74c9215e0e5387cfc09)
